### ISSUE TITLE
Displacement.__str__

### ISSUE THREAD

**Issue by heeler** [AllenCellModeling/aics-deformation#9]
In the parameter search code, the printing of the object in the iteration is exiting.
I'm thinking the _x, _y have None values in this operation and as a result when __str__ is None.

```
[2019-05-22 16:53:48,897 - root - 210][INFO] Searching 256 parameter permutations
Traceback (most recent call last):
  File "/home/jamies/anaconda3/envs/piv/bin/optimize_deformations", line 10, in <module>
    sys.exit(main())
  File "/home/jamies/anaconda3/envs/piv/lib/python3.7/site-packages/aicsdeformation/bin/optimize_deformation.py", line 28, in main
    best, all_displacements = grid_search_displacements(frame_a=img.bead_images[2], frame_b=img.bead_images[3])
  File "/home/jamies/anaconda3/envs/piv/lib/python3.7/site-packages/aicsdeformation/processing.py", line 238, in grid_search_displacements
    log.info(f"Completed {completed}%: {dfp}")
  File "/home/jamies/anaconda3/envs/piv/lib/python3.7/site-packages/aicsdeformation/processing.py", line 37, in __str__
    return f"<DisplacementFromParameters [{self.displacement}, {self.parameters}]>"
  File "/home/jamies/anaconda3/envs/piv/lib/python3.7/site-packages/aicsdeformation/types.py", line 79, in __str__
    return f"<Displacement [x:{self._x.shape}, y:{self._y.shape}, u:{self._u.shape}, sig2noise: {self.median_s2n}]>"
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by evamaxfield** [comment]
I think this can be closed? @heeler
